### ISSUE TITLE
if I add this layer it kills dash

### ISSUE THREAD

**Issue by paynito** [JorisE/evil-mu4e#3]
trying to defeat the 
`(Spacemacs) Warning: Auto-evilication could not remap these functions in map mu4e-headers-mode-map': - mu4e-headers-query-prev' originally mapped on`\'

I add this in the first main list of Melpa layers.  Then make a private layer and copy the .el there, but it kills my dash, even with the line in user-config:

`(with-eval-after-load 'org '
  (setq org-ref-completion-library 'org-ref-ivy-cite);; 
 ;; (require 'evil-mu4e)`

**Comment by JorisE** [comment]
evil-mu4e is not in use in the mu4e layer in spacemacs. There has been a PR open since february :) https://github.com/syl20bnr/spacemacs/pull/5114.

It might work if you add it to  `dotspacemacs-addititonal packages like:

```
dotspacemacs-additional-packages
   '(
evil-mu4e
)
```

I have been using evil-mu4e in the mu4e layer in spacemacs using this modification https://github.com/JorisE/spacemacs/commit/1840e76af5fd91a32b069c9b7bbe42f5cbd7814e for a long time.

**Comment by paynito** [comment]
thank you, I had tried it under  dotspacemacs-configuration-layers
I will move it to additional packages.

**Comment by JorisE** [comment]
NP, closing this issue.
